---
# Static hosts for SSHPiper routing
# Add non-Proxmox hosts here that you want accessible via SSHPiper
# (Or Proxmox hosts that need explicit IPv6 addresses)

all:
  children:
    sshpiper_static_hosts:
      hosts:
        nas.home.goodkind.io:
          ansible_host: nas.home.goodkind.io
        mini.home.goodkind.io:
          ansible_host: mini.home.goodkind.io
        mwan.home.goodkind.io:
          ansible_host: "3d06:bad:b01::113"
          ansible_host_v6: "3d06:bad:b01::113"
        # Add more static hosts here
