---
- name: Dump all variables for debugging
  hosts: proxmox
  gather_facts: false
  
  tasks:
    - name: Dump all hostvars
      ansible.builtin.debug:
        var: hostvars[inventory_hostname]
      run_once: false
